pipeline-job:
    image:
      name: scottwittenburg/spack-tutorial-builder
      entrypoint: ['']
    tags:
      - spack-kube
    before_script:
      - export SPACK_CLONE_LOCATION=$(mktemp -d)
      - pushd ${SPACK_CLONE_LOCATION}
      - git clone ${SPACK_REPO} --branch ${SPACK_REF}
      - popd
      - . "${SPACK_CLONE_LOCATION}/spack/share/spack/setup-env.sh"
    script:
      - spack ci start --cdash-token "${CDASH_AUTH_TOKEN}" --downstream-repo "${DOWNSTREAM_CI_REPO}" --branch-name "${CI_COMMIT_REF_NAME}" --commit-sha "${CI_COMMIT_SHA}"
    after_script:
      - rm -rf ${SPACK_CLONE_LOCATION}

